#!/usr/bin/env python3
"""Construct README/website SVG artwork from authored facts and the renderer palette.

Reads docs/presentation.json (authored facts), web/palette.json (generated by
the pinned web-factory renderer from web/site.json) and docs/demo-results.json
(the recorded demo run), then writes to assets/presentation/ and
web/assets/presentation/:

- the four animated light/dark SVG groups — hero, architecture, process,
  integrations — in desktop and mobile compositions, each with a fully static
  variant (no animation at all) for reduced-motion picture sources;
- the demo step terminal cards, whose command and output lines come verbatim
  from docs/demo-results.json — nothing here is invented.

Every SVG is self-contained (no script, no remote references), carries the
palette id in data-palette, and keeps a complete static frame: labels,
relationships and results survive with animations off.
"""

import json
import math
import random
import shutil
import textwrap
from html import escape
from pathlib import Path

SANS = "Arial,'PingFang SC','Noto Sans SC',sans-serif"
MONO = "ui-monospace,Menlo,Consolas,monospace"

# 装饰性动画：只做漂浮 / 透明度呼吸 / 虚线流动；reduced-motion 下全部停用，
# 静态帧仍然完整（所有标签、关系、结果都在）。
ANIMATION_CSS = """
.bt-float-a { animation: bt-float-a 7s ease-in-out infinite alternate; }
.bt-float-b { animation: bt-float-b 9s ease-in-out infinite alternate; }
.bt-breathe { animation: bt-breathe 4.5s ease-in-out infinite; }
.bt-dash { stroke-dasharray: 6 5; animation: bt-dash 2.6s linear infinite; }
@keyframes bt-float-a { from { transform: translate(0px, 0px); } to { transform: translate(6px, -9px); } }
@keyframes bt-float-b { from { transform: translate(0px, 0px); } to { transform: translate(-8px, 7px); } }
@keyframes bt-breathe { 0%, 100% { opacity: .35; } 50% { opacity: 1; } }
@keyframes bt-dash { to { stroke-dashoffset: -22; } }
@media (prefers-reduced-motion: reduce) {
  .bt-float-a, .bt-float-b, .bt-breathe, .bt-dash { animation: none; }
}
"""


def local(value):
    """zh 为主（本项目主语言），en 兜底。"""
    if isinstance(value, dict):
        return str(value.get("zh") or value.get("en") or "")
    return str(value or "")


def wrap(text, width):
    return textwrap.wrap(text, width=width) or [""]


class Painter:
    """一个主题（light/dark）下的 SVG 元素构造器。"""

    def __init__(self, mode, palette):
        self.mode = mode
        self.p = palette[mode]

    def txt(self, x, y, s, size=14, color="ink", anchor="start",
            weight=400, mono=False, opacity=None):
        extra = f" opacity='{opacity}'" if opacity is not None else ""
        return (
            f"<text x='{x}' y='{y}' fill='{self.p[color]}' font-size='{size}'"
            f" text-anchor='{anchor}' font-weight='{weight}'"
            f" font-family=\"{MONO if mono else SANS}\"{extra}>"
            f"{escape(local(s))}</text>"
        )

    def para(self, x, y, s, width_chars, size=13, color="muted", lh=1.5,
             limit=3, mono=False):
        rows = wrap(local(s), width_chars)[:limit]
        if len(wrap(local(s), width_chars)) > limit:
            rows[-1] = rows[-1].rstrip("。.") + "…"
        return "".join(
            self.txt(x, y + i * size * lh, r, size, color, mono=mono)
            for i, r in enumerate(rows)
        )

    def rect(self, x, y, w, h, fill="panel", stroke="line", rx=12,
             sw=1.2, dashed=False, opacity=None):
        extra = f" opacity='{opacity}'" if opacity is not None else ""
        dash = " stroke-dasharray='5 4'" if dashed else ""
        return (
            f"<rect x='{x}' y='{y}' width='{w}' height='{h}' rx='{rx}'"
            f" fill='{self.p[fill]}' stroke='{self.p[stroke]}'"
            f" stroke-width='{sw}'{dash}{extra}/>"
        )

    def circle(self, cx, cy, r, fill, stroke="line", sw=1.2, opacity=None,
               cls=None):
        extra = f" opacity='{opacity}'" if opacity is not None else ""
        klass = f" class='{cls}'" if cls else ""
        return (
            f"<circle cx='{cx}' cy='{cy}' r='{r}' fill='{self.p[fill]}'"
            f" stroke='{self.p[stroke]}' stroke-width='{sw}'{klass}{extra}/>"
        )

    def line(self, x1, y1, x2, y2, color="line", sw=1.1, opacity=None,
             cls=None, dasharray=None):
        extra = f" opacity='{opacity}'" if opacity is not None else ""
        klass = f" class='{cls}'" if cls else ""
        dash = f" stroke-dasharray='{dasharray}'" if dasharray else ""
        return (
            f"<line x1='{x1}' y1='{y1}' x2='{x2}' y2='{y2}'"
            f" stroke='{self.p[color]}' stroke-width='{sw}'{dash}{klass}{extra}/>"
        )

    def arrow(self, x1, y1, x2, y2, color="muted", cls="bt-dash"):
        """带箭头的连线（虚线流动表现数据在走）。"""
        head = 6
        ang = math.atan2(y2 - y1, x2 - x1)
        bx, by = x2 - head * math.cos(ang), y2 - head * math.sin(ang)
        left = (
            bx - 4 * math.cos(ang - math.pi / 2),
            by - 4 * math.sin(ang - math.pi / 2),
        )
        right = (
            bx + 4 * math.cos(ang - math.pi / 2),
            by + 4 * math.sin(ang - math.pi / 2),
        )
        pts = f"{x2},{y2} {left[0]:.1f},{left[1]:.1f} {right[0]:.1f},{right[1]:.1f}"
        return (
            self.line(x1, y1, x2, y2, color=color, cls=cls)
            + f"<polygon points='{pts}' fill='{self.p[color]}'/>"
        )

    def grid(self, w, h, step=48):
        out = []
        for x in range(step, w, step):
            out.append(self.line(x, 0, x, h, color="line", sw=0.6, opacity=0.45))
        for y in range(step, h, step):
            out.append(self.line(0, y, w, y, color="line", sw=0.6, opacity=0.45))
        return "".join(out)

    def chip(self, x, y, w, text, color="secondary", size=12.5, h=26):
        return (
            self.rect(x, y, w, h, fill="bg", stroke=color, rx=13, sw=1.1)
            + self.txt(x + w / 2, y + h / 2 + size * 0.36, text, size, color,
                       anchor="middle")
        )


def svg_document(slug, w, h, title, desc, body, palette_id, bg, animated=True):
    style = f"<style>{ANIMATION_CSS}</style>" if animated else ""
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}"'
        f' viewBox="0 0 {w} {h}" data-palette="{palette_id}" role="img"'
        f' aria-labelledby="{slug}-title {slug}-desc">'
        f'<title id="{slug}-title">{escape(title)}</title>'
        f'<desc id="{slug}-desc">{escape(desc)}</desc>{style}'
        f'<rect width="{w}" height="{h}" fill="{bg}"/>{body}</svg>\n'
    )


# ---------------------------------------------------------------------------
# 四个组合
# ---------------------------------------------------------------------------


def hero_body(painter: Painter, facts, mobile=False):
    p, g = painter, []
    hero = facts["hero"]
    if mobile:
        w, h = 460, 560
        g.append(p.grid(w, h))
        g.append(p.rect(24, 24, 64, 64, fill="panel", stroke="primary", rx=14, sw=1.4))
        g.append(p.txt(56, 66, hero["mark"], 34, "primary", anchor="middle", weight=700))
        g.append(p.txt(104, 58, facts["name"], 34, "ink", weight=700))
        g.append(p.para(104, 84, facts["tagline"], 17, size=12))
        g.append(p.para(40, 132, hero["advantage"], 24, size=13.5, color="ink"))
        x, chip_y = 40, 178
        for chip_text in hero["chips"]:
            cw = 22 + len(chip_text) * 12.5
            if x + cw > 436:  # 窄屏换行，避免溢出画布
                x, chip_y = 40, chip_y + 34
            g.append(p.chip(x, chip_y, cw, chip_text))
            x += cw + 10
        cx, cy, r = 230, 390, 118
    else:
        w, h = 960, 430
        g.append(p.grid(w, h))
        g.append(p.rect(48, 52, 66, 66, fill="panel", stroke="primary", rx=14, sw=1.4))
        g.append(p.txt(81, 97, hero["mark"], 36, "primary", anchor="middle", weight=700))
        g.append(p.txt(132, 86, facts["name"], 42, "ink", weight=700))
        g.append(p.para(133, 112, facts["tagline"], 24, size=12.5))
        g.append(p.para(50, 160, hero["advantage"], 30, size=15, color="ink"))
        x = 50
        for chip_text in hero["chips"]:
            cw = 24 + len(chip_text) * 13
            g.append(p.chip(x, 196, cw, chip_text))
            x += cw + 12
        g.append(p.txt(930, 40, "v0.1 · m1 init+run", 11.5, "muted",
                       anchor="end", mono=True))
        cx, cy, r = 716, 236, 152

    # 粒子向中心汇聚：口味是个人数据收敛出来的，而不是榜单给的
    rng = random.Random("blindtaste-hero")
    for i in range(64):
        ang = rng.uniform(0, math.tau)
        dist = rng.uniform(r * 0.42, r * 1.18)
        px_, py_ = cx + dist * math.cos(ang), cy + dist * math.sin(ang)
        if 24 < px_ < w - 24 and 24 < py_ < h - 24:
            color = rng.choice(("primary", "secondary", "highlight"))
            cls = rng.choice(("bt-float-a", "bt-float-b", None))
            if i % 3 == 0:
                g.append(p.line(px_, py_, cx, cy, color=color, sw=0.8, opacity=0.16))
            g.append(p.circle(px_, py_, rng.uniform(1.4, 2.8), color,
                              stroke="bg", sw=0.6, opacity=0.75, cls=cls))
    g.append(
        f"<circle cx='{cx}' cy='{cy}' r='46' fill='{painter.p['panel']}'"
        f" stroke='{painter.p['primary']}' stroke-width='1.6' class='bt-breathe'/>"
    )
    g.append(p.circle(cx, cy, 38, "bg", stroke="primary", sw=1.2))
    g.append(p.txt(cx, cy - 3, "你的口味", 14.5, "primary", anchor="middle", weight=600))
    g.append(p.txt(cx, cy + 16, "个人盲测收敛", 10.5, "muted", anchor="middle"))
    return w, h, "".join(g)


def architecture_body(painter: Painter, facts, mobile=False):
    p, g = painter, []
    nodes = facts["architecture"]["nodes"]
    edges = facts["architecture"]["edges"]
    if mobile:
        w, h, box_w, box_h, x = 460, 780, 340, 92, 60
        ys = [64 + i * 118 for i in range(len(nodes))]
        g.append(p.grid(w, h))
        g.append(p.txt(30, 40, facts["architecture"]["title"], 17, "ink", weight=600))
        g.append(p.txt(430, 40, "src/blindtaste", 11, "muted", anchor="end", mono=True))
        for i, node in enumerate(nodes):
            g.append(p.rect(x, ys[i], box_w, box_h, rx=12))
            g.append(p.txt(x + 18, ys[i] + 30, node["title"], 15, "ink", weight=600))
            g.append(p.para(x + 18, ys[i] + 52, node["detail"], 26, size=11.5))
        for a, b in edges:
            if b == a + 1:
                g.append(p.arrow(x + box_w / 2, ys[a] + box_h, x + box_w / 2, ys[b] - 2))
        return w, h, "".join(g)

    w, h = 960, 560
    g.append(p.grid(w, h))
    g.append(p.txt(30, 42, facts["architecture"]["title"], 18, "ink", weight=600))
    g.append(p.txt(930, 42, "src/blindtaste", 11.5, "muted", anchor="end", mono=True))
    boxes = [
        (56, 96, 190, 76),    # cli
        (330, 96, 250, 76),   # intake
        (330, 232, 250, 92),  # session
        (664, 232, 240, 92),  # providers
        (330, 392, 250, 76),  # scoring
        (664, 392, 240, 76),  # report
    ]
    for (x, y, bw, bh), node in zip(boxes, nodes):
        g.append(p.rect(x, y, bw, bh, rx=12))
        g.append(p.txt(x + 16, y + 27, node["title"], 15, "ink", weight=600))
        g.append(p.para(x + 16, y + 47, node["detail"], 27, size=11.5))
    # 数据文件标注：电池与票仓是真实落盘物
    g.append(p.chip(600, 176, 108, "battery.json", color="highlight"))
    g.append(p.chip(60, 262, 104, "votes.jsonl", color="highlight"))
    g.append(p.line(164, 262, 330, 278, color="highlight", sw=1, opacity=0.7))
    g.append(p.arrow(246, 134, 330, 134))                       # cli -> intake
    g.append(p.arrow(151, 172, 151, 278, cls=None))
    g.append(p.line(151, 278, 330, 278, color="muted", sw=1.1))  # cli -> session
    g.append(p.arrow(455, 172, 455, 230))                        # intake -> session
    g.append(p.arrow(580, 278, 662, 278))                        # session -> providers
    g.append(p.arrow(455, 324, 455, 390))                        # session -> scoring
    g.append(p.arrow(580, 430, 662, 430))                        # scoring -> report
    g.append(p.txt(480, 40, "票仓按 trial_id 去重 · 断点续跑", 11, "muted", anchor="end", mono=True))
    return w, h, "".join(g)


def process_body(painter: Painter, facts, mobile=False):
    p, g = painter, []
    steps = facts["process"]["steps"]
    if mobile:
        w, h, cw, x = 460, 700, 380, 40
        g.append(p.grid(w, h))
        g.append(p.txt(30, 40, facts["process"]["title"], 17, "ink", weight=600))
        ys = [66 + i * 116 for i in range(len(steps))]
        for i, (step, y) in enumerate(zip(steps, ys)):
            g.append(p.rect(x, y, cw, 96, rx=12))
            g.append(p.circle(x + 30, y + 30, 14, "bg", stroke="primary", sw=1.2))
            g.append(p.txt(x + 30, y + 35, str(i + 1), 13, "primary",
                           anchor="middle", weight=600))
            g.append(p.txt(x + 56, y + 35, step["title"], 15, "ink", weight=600))
            g.append(p.para(x + 56, y + 57, step["detail"], 22, size=11.5))
            if i < len(steps) - 1:
                g.append(p.arrow(x + cw / 2, y + 96, x + cw / 2, y + 114))
        y = h - 96
        g.append(p.rect(x, y, cw, 72, fill="code", stroke="line", rx=10))
        g.append(p.txt(x + 16, y + 28, "记录（docs/demo-results.json）", 11, "muted", mono=True))
        g.append(p.para(x + 16, y + 50, facts["process"]["result"], 42, size=11.5, color="ink"))
        return w, h, "".join(g)

    w, h = 960, 430
    g.append(p.grid(w, h))
    g.append(p.txt(30, 42, facts["process"]["title"], 18, "ink", weight=600))
    g.append(p.txt(930, 42, "blindtaste init && blindtaste run", 11.5, "muted",
                   anchor="end", mono=True))
    cw, ch, y = 192, 158, 96
    xs = [48, 276, 504, 732]
    for i, (step, x) in enumerate(zip(steps, xs)):
        g.append(p.rect(x, y, cw, ch, rx=12))
        g.append(p.circle(x + 30, y + 32, 14, "bg", stroke="primary", sw=1.2))
        g.append(p.txt(x + 30, y + 37, str(i + 1), 13, "primary",
                       anchor="middle", weight=600))
        g.append(p.txt(x + 54, y + 37, step["title"], 15, "ink", weight=600))
        g.append(p.para(x + 20, y + 66, step["detail"], 15, size=11.5))
        if i == 1:  # 盲选卡片里给一个匿名 A/B 的示意
            ay = y + 96
            g.append(p.rect(x + 22, ay, 66, 34, fill="bg", stroke="primary", rx=8, sw=1.1))
            g.append(p.txt(x + 55, ay + 22, "回答 A", 12, "primary", anchor="middle"))
            g.append(p.rect(x + 104, ay, 66, 34, fill="bg", stroke="secondary", rx=8, sw=1.1))
            g.append(p.txt(x + 137, ay + 22, "回答 B", 12, "secondary", anchor="middle"))
        if i < 3:
            g.append(p.arrow(x + cw + 6, y + ch / 2, xs[i + 1] - 8, y + ch / 2))
    ry = 306
    g.append(p.rect(48, ry, 876, 84, fill="code", stroke="line", rx=10))
    g.append(p.txt(66, ry + 28, "记录（docs/demo-results.json）", 11, "muted", mono=True))
    g.append(p.para(66, ry + 52, facts["process"]["result"], 92, size=12.5, color="ink"))
    return w, h, "".join(g)


def integrations_body(painter: Painter, facts, mobile=False):
    p, g = painter, []
    items = facts["integrations"]["items"]
    if mobile:
        w, h = 460, 760
        g.append(p.grid(w, h))
        g.append(p.txt(30, 40, facts["integrations"]["title"], 17, "ink", weight=600))
        cx, cy = 230, 150
        g.append(f"<circle cx='{cx}' cy='{cy}' r='64' fill='{painter.p['panel']}'"
                 f" stroke='{painter.p['primary']}' stroke-width='1.6' class='bt-breathe'/>")
        g.append(p.txt(cx, cy - 2, facts["name"], 16, "ink", anchor="middle", weight=700))
        g.append(p.txt(cx, cy + 18, "ChatAdapter", 10.5, "muted", anchor="middle", mono=True))
        y = 262
        for item in items:
            g.append(p.line(cx, cy + 64, cx, y, color="line", sw=1, opacity=0.5))
            g.append(p.rect(50, y, 360, 66, rx=10,
                            stroke="highlight" if "未验证" in item["detail"] else "line"))
            g.append(p.txt(70, y + 27, item["title"], 14.5, "ink", weight=600))
            g.append(p.txt(70, y + 48, item["detail"], 11.5, "muted"))
            y += 82
        return w, h, "".join(g)

    w, h = 960, 500
    g.append(p.grid(w, h))
    g.append(p.txt(30, 42, facts["integrations"]["title"], 18, "ink", weight=600))
    g.append(p.txt(930, 42, "key → ~/.blindtaste/keys.env", 11.5, "muted",
                   anchor="end", mono=True))
    cx, cy, ring = 480, 285, 168
    g.append(f"<circle cx='{cx}' cy='{cy}' r='{ring}' fill='none'"
             f" stroke='{painter.p['line']}' stroke-width='1' stroke-dasharray='3 6'/>")
    g.append(f"<circle cx='{cx}' cy='{cy}' r='80' fill='{painter.p['panel']}'"
             f" stroke='{painter.p['primary']}' stroke-width='1.6' class='bt-breathe'/>")
    g.append(p.txt(cx, cy - 2, facts["name"], 17, "ink", anchor="middle", weight=700))
    g.append(p.txt(cx, cy + 20, "ChatAdapter 统一接口", 11, "muted", anchor="middle"))
    chip_w, chip_h = 208, 58
    for k, item in enumerate(items):
        ang = math.radians(-90 + k * 60)
        px_ = cx + ring * math.cos(ang)
        py_ = cy + ring * math.sin(ang)
        g.append(p.line(cx + 80 * math.cos(ang), cy + 80 * math.sin(ang),
                        px_, py_, color="line", sw=1, opacity=0.6))
        x = px_ - chip_w / 2
        y = py_ - chip_h / 2
        unverified = "未验证" in item["detail"]
        demo = item["title"].startswith("--demo")
        g.append(p.rect(x, y, chip_w, chip_h, rx=10,
                        stroke="highlight" if unverified else "line",
                        dashed=demo))
        g.append(p.txt(x + 16, y + 24, item["title"], 14, "ink", weight=600))
        g.append(p.txt(x + 16, y + 44, item["detail"], 11, "muted"))
    return w, h, "".join(g)


# ---------------------------------------------------------------------------
# 演示步骤卡片：命令与输出逐字来自 docs/demo-results.json
# ---------------------------------------------------------------------------


def demo_card(painter: Painter, step, max_lines=13):
    p, g = painter, []
    command = step["command"].replace("\\n", " ⏎ ")
    lines = step["output"].splitlines()
    shown = lines[:max_lines]
    truncated = len(lines) > max_lines
    w = 780
    bar_h, pad = 40, 18
    h = bar_h + pad + 24 + (len(shown) + (2 if truncated else 1)) * 20 + pad
    g.append(p.rect(0, 0, w, h, fill="code", stroke="line", rx=12, sw=1))
    for i, dot in enumerate((12, 30, 48)):
        g.append(p.circle(dot, bar_h / 2, 4.5, "muted", stroke="code", sw=0))
    g.append(p.txt(70, bar_h / 2 + 4, local(step["label"]), 12, "muted", mono=True))
    g.append(p.line(0, bar_h, w, bar_h, color="line", sw=1))
    y = bar_h + pad + 14
    g.append(p.txt(pad, y, "$ " + command, 12.5, "primary", mono=True))
    y += 24
    for line in shown:
        color = "ink"
        if "✓" in line or "揭晓" in line:
            color = "secondary"
        g.append(p.txt(pad + 12, y, line[:92], 12, color, mono=True, weight=600
                       if color == "secondary" else 400))
        y += 20
    if truncated:
        g.append(p.txt(pad + 12, y, f"……（其余 {len(lines) - max_lines} 行见"
                                    f" docs/demo-results.json）", 11.5, "muted", mono=True))
    return w, h, "".join(g)


# ---------------------------------------------------------------------------


def main() -> None:
    repo = Path(__file__).resolve().parent.parent
    facts = json.loads((repo / "docs/presentation.json").read_text(encoding="utf-8"))
    palette = json.loads((repo / "web/palette.json").read_text(encoding="utf-8"))
    record = json.loads((repo / "docs/demo-results.json").read_text(encoding="utf-8"))
    assert 3 <= len(facts["architecture"]["nodes"]) <= 6
    assert 3 <= len(facts["process"]["steps"]) <= 4
    assert 3 <= len(facts["integrations"]["items"]) <= 6

    targets = [repo / "assets/presentation", repo / "web/assets/presentation"]
    for folder in targets:
        folder.mkdir(parents=True, exist_ok=True)

    def save(slug, w, h, title, desc, body, animated=True):
        doc = svg_document(slug, w, h, title, desc, body, palette["id"],
                           palette[mode]["bg"], animated)
        for folder in targets:
            (folder / f"{slug}.svg").write_text(doc, encoding="utf-8")

    for mode in ("light", "dark"):
        pt = Painter(mode, palette)
        zh = mode == "dark"
        suffix = "深色" if zh else "浅色"
        hero_w, hero_h, hero = hero_body(pt, facts)
        save(f"hero-{mode}", hero_w, hero_h,
             f"{facts['name']} 品牌主视觉（{suffix}）",
             "粒子向「你的口味」汇聚：个人盲测把零散任务收敛成稳定偏好。",
             hero)
        save(f"hero-static-{mode}", hero_w, hero_h,
             f"{facts['name']} 品牌主视觉静态版（{suffix}）",
             "与动画版同构的完整静态帧，供减少动态偏好使用。", hero, animated=False)
        mw, mh, mbody = hero_body(pt, facts, mobile=True)
        save(f"hero-mobile-{mode}", mw, mh,
             f"{facts['name']} 品牌主视觉窄屏版（{suffix}）",
             "窄屏竖排构图，事实与桌面版一致。", mbody)

        aw, ah, abody = architecture_body(pt, facts)
        save(f"architecture-{mode}", aw, ah,
             f"{facts['name']} 架构蓝图（{suffix}）",
             "cli、intake、session、providers、scoring、report 的数据流，"
             "电池与票仓是真实落盘物。", abody)
        save(f"architecture-static-{mode}", aw, ah,
             f"{facts['name']} 架构蓝图静态版（{suffix}）",
             "与动画版同构的完整静态帧。", abody, animated=False)
        mw, mh, mbody = architecture_body(pt, facts, mobile=True)
        save(f"architecture-mobile-{mode}", mw, mh,
             f"{facts['name']} 架构窄屏版（{suffix}）",
             "窄屏纵向数据流，事实与桌面版一致。", mbody)

        pw, ph, pbody = process_body(pt, facts)
        save(f"process-{mode}", pw, ph,
             f"{facts['name']} 盲测流程（{suffix}）",
             "init 建电池、run 匿名盲选、投票落盘、续跑与揭晓；结果条来自"
             "docs/demo-results.json 的真实记录。", pbody)
        save(f"process-static-{mode}", pw, ph,
             f"{facts['name']} 盲测流程静态版（{suffix}）",
             "与动画版同构的完整静态帧。", pbody, animated=False)
        mw, mh, mbody = process_body(pt, facts, mobile=True)
        save(f"process-mobile-{mode}", mw, mh,
             f"{facts['name']} 盲测流程窄屏版（{suffix}）",
             "窄屏纵向流程，事实与桌面版一致。", mbody)

        iw, ih, ibody = integrations_body(pt, facts)
        save(f"integrations-{mode}", iw, ih,
             f"{facts['name']} 模型接入（{suffix}）",
             "五家官方 OpenAI 兼容端点与离线演示适配器，"
             "统一在 ChatAdapter 接口后面。", ibody)
        save(f"integrations-static-{mode}", iw, ih,
             f"{facts['name']} 模型接入静态版（{suffix}）",
             "与动画版同构的完整静态帧。", ibody, animated=False)
        mw, mh, mbody = integrations_body(pt, facts, mobile=True)
        save(f"integrations-mobile-{mode}", mw, mh,
             f"{facts['name']} 模型接入窄屏版（{suffix}）",
             "窄屏纵向接入列表，事实与桌面版一致。", mbody)

        for step in record["steps"]:
            dw, dh, dbody = demo_card(pt, step)
            save(f"demo-{step['id']}-{mode}", dw, dh,
                 f"{facts['name']} 演示步骤 {step['id']}（{suffix}）",
                 f"命令与输出逐字取自 docs/demo-results.json：{local(step['label'])}。",
                 dbody, animated=False)

    print("presentation SVGs written to assets/presentation and web/assets/presentation")


if __name__ == "__main__":
    main()
